
$background = rgb(18181A)
$foreground = rgb(ECDEFC)
$color0 = rgb(3F3F42)
$color1 = rgb(12111A)
$color2 = rgb(1A1824)
$color3 = rgb(4C3F5F)
$color4 = rgb(534362)
$color5 = rgb(765F90)
$color6 = rgb(977AB8)
$color7 = rgb(DCC8F2)
$color8 = rgb(9A8CA9)
$color9 = rgb(181723)
$color10 = rgb(232030)
$color11 = rgb(65547F)
$color12 = rgb(6E5A83)
$color13 = rgb(9D7FC1)
$color14 = rgb(C9A2F5)
$color15 = rgb(DCC8F2)
