# : Manager [[[

[mgr]
cwd = { fg = "#efdee0" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ffa657", bg = "#ffa657" }
marker_cut      = { fg = "#ffdcbd", bg = "#ffdcbd" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ecbe91", bg = "#ecbe91" }

# Count
count_copied   = { fg = "#2c1600", bg = "#ffdcbd" }
count_cut      = { fg = "#2c1600", bg = "#ffdcbd" }
count_selected = { fg = "#551d2d", bg = "#ecbe91" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb1c1" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb1c1", bold = true, bg = "#191113" }
inactive  = { fg = "#e4bdc3", bg = "#191113" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb1c1", fg = "#551d2d", bold = true }
normal_alt  = { bg = "#524345", fg = "#d6c2c4" }

# Select mode
select_main = { bg = "#e4bdc3", fg = "#43292f", bold = true }
select_alt  = { bg = "#524345", fg = "#d6c2c4" }

# Unset mode
unset_main = { bg = "#ecbe91", fg = "#462a09", bold = true }
unset_alt  = { bg = "#524345", fg = "#d6c2c4" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#b85060" }
perm_write = { fg = "#c27122" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff8b24" }
perm_sep   = { fg = "#ff405e" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb1c1", bg = "#413738" }
progress_error  = { fg = "#ffb4ab", bg = "#413738" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413738" }
cand = { fg = "#ffb1c1" }
rest = { fg = "#551d2d" }
desc = { fg = "#efdee0" }
separator = " ▶ "
separator_style = { fg = "#efdee0" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#ecbe91" }
title_warn  = { fg = "#ffb1c1" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb1c1" }
active = { fg = "#ecbe91", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb1c1" }
value  = { fg = "#efdee0" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb1c1", bg = "#551d2d" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb1c1" }
title   = {}
hovered = { fg = "#ffdcbd", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#efdee0" }
run    = { fg = "#efdee0" }
footer = { fg = "#43292f", bg = "#e4bdc3" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    # Fallback
    { url = "*", fg = "#efdee0" },
    { url = "*/", fg = "#ffb1c1" },
]

# : ]]]
